name: personal_portfolio
description: Portfolio for Hiba Hashem — Senior Flutter Developer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  go_router: ^15.1.2
  url_launcher: ^6.3.1
  flutter_screenutil: ^5.9.3
  meta_seo: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/resume.pdf
    - assets/avatar.png
    - assets/projects/aec/
    - assets/projects/blckout/
    - assets/projects/maalpay/
    - assets/projects/knotify/
    - assets/projects/jumlatech/
    - assets/projects/etloob/
